# Standards: 0.11
---

# 4.1.3 Ensure auditing for processes that start prior to auditd is enabled

- name: 4.1.3 Ensure auditing for processes that start prior to auditd is enabled
  replace:
    dest: /etc/default/grub
    regexp: '(^GRUB_CMDLINE_LINUX\s*\=\s*)(?:")(.+)(?<!audit=1)(?:")'
    replace: '\1"\2 audit=1"'
  notify: grub2cfg
  tags:
    - "4.1.3"
    - level-2
    - section-4
    - scored
